<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'format' => [

        'full' => 'r',
        'short' => 'd.m.y g:ia',
        'medium' => 'M j Y, g:i a',
        'long' => 'F j, Y, g:i a'

    ],

];
